# Generated by Django 6.0.3 on 2026-04-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('monthly_fuel_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekly_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subsidy_received', models.BooleanField(default=False)),
                ('subsidy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('satisfaction_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Maddy.city')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
